version: "3.7"
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes: 
      - ../db:/data/db
    ports:
      - 27017:27017